# Generated by Django 5.0.1 on 2024-03-05 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('image_url', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
